version: '3'
services:

  wp-db:
    image: mysql:5.7

    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    volumes:
      - storage-mysql:/var/lib/mysql

    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE     : wordpress # WORDPRESS_DB_NAMEと合わせる
      MYSQL_ROOT_PASSWORD: root      # ルートパスワード
      MYSQL_USER         : wpuser    # WORDPRESS_DB_USERと合わせる
      MYSQL_PASSWORD     : pass      # WORDPRESS_DB_PASSWORDと合わせる
      TZ                 : 'Asia/Tokyo'

  wp:
    image: wordpress:php7.3-fpm

    volumes:
      - ./wp:/var/www/html

    expose:
      - "9000"

    environment:
      WORDPRESS_DB_HOST     : wp-db     # mysqlコンテナを指定
      WORDPRESS_DB_USER     : wpuser    # MYSQL_USERと合わせる
      WORDPRESS_DB_PASSWORD : pass      # MYSQL_PASSWORDと合わせる
      WORDPRESS_DB_NAME     : wordpress # MYSQL_DATABASEと合わせる
      WORDPRESS_TABLE_PREFIX: basis

    links:
      - wp-db

  wp-nginx:
    image: nginx:1.17
    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./wp:/var/www/html

    links:
      - wp # wordpress起動後でないとnginxがnot foundで落ちる

volumes:
  storage-mysql:
